name: linter check
run-name: ${{ github.actor }} is testing out checkPR
on:
  pull_request:
    branches: [ master ]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with: 
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v5